### ISSUE TITLE
Client side crash after new update

### ISSUE THREAD

**Issue by TacticalUniverse** [NicJames2378/IEClocheCompat#6]
https://paste.dimdev.org/odadozaneb.mccrash

**Comment by NicJames2378** [comment]
I have been unable to reproduce your error. Please try with this version and see if your error persists. If it does, contact me through [this](https://discord.gg/vFBVWFY) Discord link so I may troubleshoot this further.
[IE Cloche Compat 2.1.7-d.350.zip](https://github.com/NicJames2378/IEClocheCompat/files/2734983/IE.Cloche.Compat.2.1.7-d.350.zip)

**Comment by ate0ate** [comment]
I am also getting this same crash in a custom pack. Quite large. Will try the version provided above and report back.

**Comment by ate0ate** [comment]
That version provided above seems to work perfectly for me thus far. Thanks!

**Comment by phantom1151** [comment]
there is one problem with this d350. they willk not let you upload it to the site. because this release of the mod in not on the launcher to start with

**Comment by SenilePenguin** [comment]
Issue corrected in new CurseForge release. Should be approved and available within the next few hours.
